<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageVersion Include="NSubstitute" Version="6.2.0" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageVersion Include="CommunityToolkit.Diagnostics" Version="8.4.2" />
    <PackageVersion Include="CommunityToolkit.HighPerformance" Version="8.4.2" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <PackageVersion Include="FlatSharp.Compiler" Version="7.9.0" />
    <PackageVersion Include="FlatSharp.Runtime" Version="7.9.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageVersion Include="Spectre.Console" Version="0.57.2" />
    <PackageVersion Include="Spectre.Console.Cli" Version="0.57.2" />
  </ItemGroup>

  <ItemGroup>
    <PackageVersion Include="DotNet.Glob" Version="3.1.3" />
  </ItemGroup>

  <ItemGroup>
    <PackageVersion Include="Serilog.AspNetCore" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="12.1.3" />
    <PackageVersion Include="Avalonia.Desktop" Version="12.1.3" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="12.1.3" />
  </ItemGroup>

  <ItemGroup>
    <PackageVersion Include="ShadUI" Version="0.2.4" />
  </ItemGroup>

</Project>
